### ISSUE TITLE
Overview document

### ISSUE THREAD

**Issue by maxidor** [thegridprotocol/thegrid#1]
Create an overview document to provide background on:
- Why/how The Grid project came to be
- Its intended goals and values
- Differences with the Matrix protocol
- The high-level methodology/processes we want to put in place to ensure this protocol and project are successful
- The set of first priorities that will be worked on

**Comment by maxidor** [comment]
Current draft is hosted as:
- [Google Docs](https://docs.google.com/document/d/1Zlh-QBvwIyhkUrBjav3sVeuHFxfExwBXaZf47dmHNtE) - open to comments and suggestions
- [PDF](https://kamax.io/thegrid-sunrise_overview.pdf) - generated from the Google Docs, read-only, might be outdated

Will be integrated into the protocol website once finalized.

**Comment by Half-Shot** [comment]
Same as https://github.com/thegridprotocol/thegrid/issues/2#issuecomment-431179615

**Comment by maxidor** [comment]
Doc is now considered final and available as [PDF](https://kamax.io/grid/thegrid-sunrise_overview.pdf).
