### ISSUE TITLE
Governing body document

### ISSUE THREAD

**Issue by maxidor** [thegridprotocol/thegrid#2]
Create a document to outline the high level concepts and guidance principles of the governing body of The Grid that will be used for the articles of constitution.

**Comment by maxidor** [comment]
Current draft is hosted as:
- [Google Docs](https://docs.google.com/document/d/1dpzX9PzWEsvKjShah32S6Waea88ID63zfk6NqKDCD3U) - open to comments and suggestions

Will be integrated into the protocol website once finalized.

**Comment by Half-Shot** [comment]
Worth pointing out that the Google Doc is no longer open to comments or suggestions, and that there isn't a record of any comments or suggestions for mem to follow?

**Comment by maxidor** [comment]
Doc is now considered final and available as [PDF](https://kamax.io/grid/thegrid-governing_body.pdf).
