### ISSUE TITLE
Documentation principles document

### ISSUE THREAD

**Issue by maxidor** [thegridprotocol/thegrid#3]
Create a document that will outline the management of the specification and *documentation* in general for the project.

**Comment by maxidor** [comment]
Current draft is hosted as:
- [Google Docs](https://docs.google.com/document/d/1kypS56JuhpDyHXkeRoESf1nLfkiRVnGf2Qenl0o1bW8) - Work in Progress

Will be integrated into the protocol website once finalized.

**Comment by Half-Shot** [comment]
Same as https://github.com/thegridprotocol/thegrid/issues/2#issuecomment-431179615

**Comment by maxidor** [comment]
Doc is now considered final and available as [PDF](https://kamax.io/grid/thegrid-documentation_principles.pdf).
